# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aC-CJk3MLdKZZ3cgMZAUIzRwW7IMkX_U
"""

#Assignment1: Considering two variables x & y, find x^y

x=int(input("Enter first number:"))
y=int(input("Enter second number:"))
print(pow(x,y))

#Easier method

a=int(input("Enter first number:"))
b=int(input("Enter second number"))
print(a**b)

